import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { bgColor } from "@/data/constants";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, // etai page.tsx
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-bgColor text-white">
        {children}       
      </body>
    </html>
  );
}
