// export const Categories = {
//   Housing: "Housing",
//   Transportation: "Transportation",
//   Food: "Food",
//   Healthcare: "Healthcare",
//   Insurance: "Insurance",
//   Debt_Payments: "Debt Payments",
//   Savings_and_Investments: "Savings and Investments",
//   Personal_Care: "Personal Care",
//   Entertainment_and_Recreation: "Entertainment and Recreation",
//   Education: "Education",
//   Childcare_and_Education: "Childcare and Education",
//   Clothing_and_Accessories: "Clothing and Accessories",
//   Gifts_and_Donations: "Gifts and Donations",
//   Pets: "Pets",
//   Miscellaneous: "Miscellaneous",
// };

export enum Categories {
  Housing = "Housing",
  Transportation = "Transportation",
  Food = "Food",
  Healthcare = "Healthcare",
  Insurance = "Insurance",
  Debt_Payments = "Debt Payments",
  Savings_and_Investments = "Savings and Investments",
  Personal_Care = "Personal Care",
  Entertainment_and_Recreation = "Entertainment and Recreation",
  Education = "Education",
  Childcare_and_Education = "Childcare and Education",
  Clothing_and_Accessories = "Clothing and Accessories",
  Gifts_and_Donations = "Gifts and Donations",
  Pets = "Pets",
  Miscellaneous = "Miscellaneous",
}
